name: Build Docker Image

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          # Will change it to true once we have added a Docker Hub repository
          # and its credentials to GitHub Secrets.
          tags: taldate-docker-image:latest
